
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-resources/api-docs

feign:
  hystrixConfig:
    "hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds": 8000
    "hystrix.command.GithubConnector#getRepos.execution.isolation.thread.timeoutInMilliseconds": 15000
  endpointConfig:
    GithubConnector:
      default:
        url: https://api.github.com
        readTimeoutMillis: 8000
        connectTimeoutMillis: 5000
      getRepos:
        url: https://api.github.com
        readTimeoutMillis: 15000
        connectTimeoutMillis: 10000